### ISSUE TITLE
界面上不能同步名字，也不能自定义

### ISSUE THREAD

**Issue by kylinfedora** [houselabs/home-assistant-mideaccm#5]
界面上不能同步名字，也不能自定义，请问怎么才能像你论坛里截图那样。谢谢！

![image](https://user-images.githubusercontent.com/2525979/52901619-e30bae00-3240-11e9-8913-fb0193163e54.png)

![image](https://user-images.githubusercontent.com/2525979/52901628-f585e780-3240-11e9-845c-2d7ba59789c0.png)

**Comment by BH4WHN** [comment]
这个需要在customize.yaml自定义每个空调的名字
climate.mideaccm_a1:
  friendly_name: 客厅空调
以此类推

**Comment by kylinfedora** [comment]
> 这个需要在customize.yaml自定义每个空调的名字
> climate.mideaccm_a1:
> friendly_name: 客厅空调
> 以此类推

谢谢，我看看
