### ISSUE TITLE
Climate组件发生重大更新，插件已无法运行。

### ISSUE THREAD

**Issue by BH4WHN** [houselabs/home-assistant-mideaccm#6]
受影响版本：homeassistant >0.95.0 
参考信息：
Climate 1.0 #23899 [https://github.com/home-assistant/home-assistant/pull/23899](url)
Climate Cleanup [https://developers.home-assistant.io/blog/2019/07/03/climate-cleanup.html](url)
@ohsc 请大神抽空更新插件，谢谢！

**Comment by BH4WHN** [comment]
已修复，回国后上传更新

**Comment by ohsc** [comment]
我修了一版，还没测过
